name: docker-compose-deploy
on:
    workflow_call:

jobs:
    docker-compose:
        env:
            user: ${{vars.DOCKERHUB_USER}}
            pass: ${{secrets.DOCKERHUB_PASS}}
            commit: ${{ github.sha }}
        runs-on: self-host

        steps:
            - name: checkout code
              uses: actions/checkout@v6
            
            - name: docker compose
              run: docker compose up -d --build --force-recreate

            - name: wait for 2 minutes.
              run: sleep 120s
            
            - name: run docker compose down
              run: docker compose down
