name: workflow_name

on:
    workflow_call:

jobs:
    test_hello:
        runs-on: ubuntu-latest

        steps:
          - name: say hello to dosto
            run: echo "hello dosto0"
              


