name: workflow_name

on:
    workflow_dispatch:

jobs:
    code-test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.12","3.13"]



        steps:
          - name: checkout code
            uses: actions/checkout@v6

          - name: setup python ${{matrix.python-version}}
            uses: actions/setup-python@v6
            with:
                python-version: ${{matrix.python-version}}

          - name: install dependencies
            run: pip install -r requirements.txt

          - name: run lint test
            run: flake8 app.py
        
    docker:
        needs: [code-test]
        env:
            user: ${{vars.DOCKERHUB_USER}}
            pass: ${{secrets.DOCKERHUB_PASS}}
            commit: ${{ github.sha }}

        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v6

            - name: docker login
              uses: docker/login-action@v4
              with:
                username: ${{env.user}}
                password: ${{env.pass}}
                

            - name: setup QEMU
              uses: docker/setup-qemu-action@v4

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v4
            
            - name: Build and Push docker 
              uses: docker/build-push-action@v7
              with:
                context: .
                push: true
                tags: ${{env.user}}/flask_gitactions:${{ env.commit }}
            
            - name: trivy scan 
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: ${{env.user}}/flask_gitactions:${{ env.commit }}
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

    docker-compose:
        needs: [docker]
        uses: ./.github/workflows/compose-deploy.yml

              


